In [3]:
from sqlalchemy import create_engine, text

In [4]:
database_name = 'prescribers'    # Fill this in with your lahman database name

connection_string = f"postgresql://postgres:postgres@localhost:5432/{database_name}"

In [3]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\epicwork\anaconda3\lib\site-packages (2.9.11)

In [5]:
engine = create_engine(connection_string)

In [6]:
import pandas as pd

In [83]:
query = 'SELECT * FROM prescriber'

In [16]:
with engine.connect() as connection:
    prescriber = pd.read_sql(text(query), con = connection)

prescriber.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,nppes_provider_zip5,nppes_provider_zip4,nppes_provider_state,nppes_provider_country,specialty_description,description_flag,medicare_prvdr_enroll_status
0,1.003000e+09,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,37243,0001,TN,US,Nurse Practitioner,S,N
1,1.003012e+09,CUDZILO,COREY,None,M.D.,M,I,2240 SUTHERLAND AVE,SUITE 103,KNOXVILLE,37919,2333,TN,US,Pulmonary Disease,S,E
2,1.003013e+09,GRABENSTEIN,WILLIAM,P,M.D.,M,I,1822 MEMORIAL DR,None,CLARKSVILLE,37043,4605,TN,US,Family Practice,S,E
3,1.003014e+09,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,None,NASHVILLE,37203,2786,TN,US,Orthopedic Surgery,S,E
4,1.003018e+09,TODD,JOSHUA,W,M.D.,M,I,1819 W CLINCH AVE,SUITE 108,KNOXVILLE,37916,2435,TN,US,Cardiology,S,E

<h1>Deaths over time</h1>

<h2>How has total overdose deaths changed over time?</h2>

In [30]:
od_query = 'SELECT year, SUM(overdose_deaths) FROM overdose_deaths GROUP BY year ORDER BY year'

In [31]:
with engine.connect() as connection:
    overdose_deaths = pd.read_sql(text(od_query), con = connection)

overdose_deaths

   year   sum
0  2015  1033
1  2016  1186
2  2017  1267
3  2018  1304

The number of overdose deaths has grown steadily over the four years present in the data

<h2>How have overdose deaths changed over time for Davidson and Shelby counties.</h2>

In [57]:
dav_od_query = '''SELECT year, county, SUM(overdose_deaths)
                FROM overdose_deaths
                LEFT JOIN fips_county ON CAST(overdose_deaths.fipscounty AS varchar) = CAST(fips_county.fipscounty AS varchar)
                WHERE county = 'DAVIDSON' OR county = 'SHELBY'
                GROUP BY year, county
                ORDER BY county, year'''

In [58]:
with engine.connect() as connection:
    dav_od = pd.read_sql(text(dav_od_query), con = connection)

dav_od

   year    county  sum
0  2015  DAVIDSON  127
1  2016  DAVIDSON  178
2  2017  DAVIDSON  184
3  2018  DAVIDSON  200
4  2015    SHELBY  135
5  2016    SHELBY  150
6  2017    SHELBY  159
7  2018    SHELBY  123

The number of deaths in Davidson County is increasing over time. In Shelby county, the number of deaths increased from 2015-2017 but decreased significantly in 2018.

<h2>Are there any counties in which overdose deaths are trending downward?</h2>

In [73]:
trend_query = '''SELECT year, county, SUM(overdose_deaths) AS overdose_deaths
                FROM overdose_deaths
                LEFT JOIN fips_county ON CAST(overdose_deaths.fipscounty AS varchar) = CAST(fips_county.fipscounty AS varchar)
                GROUP BY year, county
                ORDER BY county, year'''

with engine.connect() as connection:
    trend_od = pd.read_sql(text(trend_query), con = connection)

trend_od['year shift'] = trend_od['year'].shift(3)
trend_od['county shift'] = trend_od['county'].shift(3)
trend_od['overdose_shift'] = trend_od['overdose_deaths'].shift(3)
trend_od = trend_od.loc[trend_od['county'] == trend_od['county shift']]
trend_od['overdose_shift'] = trend_od['overdose_shift'].astype(int)
trend_od['year shift'] = trend_od['year shift'].astype(int)
trend_od['trend'] = trend_od['overdose_deaths'] - trend_od['overdose_shift']
trend_od = trend_od.loc[trend_od['trend'] < 0]
trend_od

,year,county,overdose_deaths,year shift,county shift,overdose_shift,trend
3,2018,ANDERSON,18,2015,ANDERSON,20,-2
7,2018,BEDFORD,7,2015,BEDFORD,8,-1
11,2018,BENTON,1,2015,BENTON,4,-3
27,2018,CAMPBELL,3,2015,CAMPBELL,16,-13
35,2018,CARROLL,0,2015,CARROLL,1,-1
47,2018,CHESTER,1,2015,CHESTER,3,-2
51,2018,CLAIBORNE,1,2015,CLAIBORNE,3,-2
55,2018,CLAY,1,2015,CLAY,2,-1
83,2018,DECATUR,2,2015,DECATUR,5,-3
87,2018,DICKSON,10,2015,DICKSON,16,-6
91,2018,DYER,0,2015,DYER,1,-1
95,2018,FAYETTE,4,2015,FAYETTE,5,-1
99,2018,FENTRESS,1,2015,FENTRESS,2,-1
103,2018,FRANKLIN,1,2015,FRANKLIN,7,-6
111,2018,GILES,4,2015,GILES,9,-5
115,2018,GRAINGER,1,2015,GRAINGER,2,-1
127,2018,HAMBLEN,7,2015,HAMBLEN,11,-4
143,2018,HARDIN,5,2015,HARDIN,7,-2
147,2018,HAWKINS,11,2015,HAWKINS,14,-3
171,2018,HUMPHREYS,1,2015,HUMPHREYS,4,-3
175,2018,JACKSON,2,2015,JACKSON,3,-1
183,2018,JOHNSON,1,2015,JOHNSON,3,-2
211,2018,LOUDON,7,2015,LOUDON,9,-2
215,2018,MACON,2,2015,MACON,3,-1
223,2018,MARION,1,2015,MARION,3,-2
239,2018,MC NAIRY,0,2015,MC NAIRY,9,-9
259,2018,MORGAN,3,2015,MORGAN,10,-7
279,2018,POLK,0,2015,POLK,3,-3
283,2018,PUTNAM,8,2015,PUTNAM,12,-4
287,2018,RHEA,2,2015,RHEA,3,-1
295,2018,ROBERTSON,10,2015,ROBERTSON,12,-2
303,2018,SCOTT,1,2015,SCOTT,4,-3
315,2018,SHELBY,123,2015,SHELBY,135,-12
319,2018,SMITH,3,2015,SMITH,5,-2
347,2018,UNION,2,2015,UNION,3,-1
355,2018,WARREN,4,2015,WARREN,5,-1
359,2018,WASHINGTON,9,2015,WASHINGTON,17,-8
371,2018,WHITE,4,2015,WHITE,7,-3
379,2018,WILSON,19,2015,WILSON,26,-7

<h1>Spending on opioids</h1>

<h2>What is the correlation between spending on opioids and overdose deaths?</h2>

In [28]:
county_query = '''SELECT county FROM fips_county'''

with engine.connect() as connection:
    county_list = pd.read_sql(text(county_query), con = connection)

county_list = county_list.sort_values(by = 'county').reset_index(drop = True)
county_list

         county
0     ABBEVILLE
1        ACADIA
2      ACCOMACK
3           ADA
4         ADAIR
...         ...
3267       YUMA
3268       YUMA
3269     ZAPATA
3270     ZAVALA
3271    ZIEBACH

[3272 rows x 1 columns]

In [19]:
spend_query = '''SELECT fips_county.county, SUM(prescription.total_drug_cost) AS opioid_spending
                FROM prescriber
                LEFT JOIN zip_fips ON nppes_provider_zip5 = zip_fips.fipscounty
                LEFT JOIN fips_county USING(fipscounty)
                LEFT JOIN prescription USING(npi)
                LEFT JOIN drug USING(drug_name)
                WHERE county IS NOT NULL AND opioid_drug_flag = 'Y'
                GROUP BY fips_county.county
                ORDER BY fips_county.county'''

with engine.connect() as connection:
    spend_od = pd.read_sql(text(spend_query), con = connection)

#spend_od = spend_od.sort_values(by = 'opioid_spending', ascending = False)

spend_od['opioid_spending'] = spend_od['opioid_spending'].map("${:,.2f}".format)
spend_od.head()

     county opioid_spending
0     ADAMS     $134,436.05
1  BEAUFORT  $33,964,663.74
2    BERTIE     $925,881.80
3    BOWMAN     $275,815.55
4  CABARRUS     $314,190.27

In [21]:
death_query = '''SELECT fc.county, SUM(overdose_deaths) as overdoses
                FROM overdose_deaths
                LEFT JOIN fips_county AS fc ON CAST(overdose_deaths.fipscounty AS varchar) = CAST(fc.fipscounty AS varchar)
                WHERE county IS NOT NULL
                GROUP BY fc.county
                ORDER BY fc.county'''

with engine.connect() as connection:
    death_od = pd.read_sql(text(death_query), con = connection)

death_od

        county  overdoses
0     ANDERSON         96
1      BEDFORD         19
2       BENTON         11
3      BLEDSOE          8
4       BLOUNT         99
..         ...        ...
90       WAYNE          8
91     WEAKLEY         14
92       WHITE         19
93  WILLIAMSON         94
94      WILSON         98

[95 rows x 2 columns]

<h2>What is the ratio for spending on opioid vs non-opioid prescriptions?</h2>

<h2>Are those who spend a higher ratio on opioids suffering from more deaths?</h2>

<h1>Per Capita</h1>

<h2>Which county has the highest overdose deaths per capita?</h2>

In [29]:
death_percap_query = '''SELECT fc.county, population, od.overdose_deaths
                FROM population
                LEFT JOIN fips_county AS fc USING(fipscounty)
                LEFT JOIN overdose_deaths AS od USING(fipscounty)
                GROUP BY fips_county.county'''

with engine.connect() as connection:
    death_percap = pd.read_sql(text(death_percap_query), con = connection)

death_percap

ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: character = integer
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT fc.county, population, od.overdose_deaths
                FROM population
                LEFT JOIN fips_county AS fc USING(fipscounty)
                LEFT JOIN overdose_deaths AS od USING(fipscounty)
                GROUP BY fips_county.county]
(Background on this error at: https://sqlalche.me/e/20/f405)

<h2>Which county has the most spending overall per capita?</h2>

In [15]:
spend_query = '''SELECT fips_county.county, SUM(prescription.total_drug_cost) AS opioid_spending
                FROM prescriber
                LEFT JOIN zip_fips ON nppes_provider_zip5 = zip_fips.fipscounty
                LEFT JOIN fips_county USING(fipscounty)
                LEFT JOIN prescription USING(npi)
                LEFT JOIN drug USING(drug_name)
                WHERE county IS NOT NULL
                GROUP BY fips_county.county'''

with engine.connect() as connection:
    spend_od = pd.read_sql(text(spend_query), con = connection)

spend_od = spend_od.sort_values(by = 'opioid_spending', ascending = False)

spend_od['opioid_spending'] = spend_od['opioid_spending'].map("${:,.2f}".format)
spend_od.head()

         county    opioid_spending
6       FORSYTH  $1,291,220,328.30
40  NEW HANOVER    $616,707,048.60
8          CASS    $417,288,904.80
24      HAYWOOD    $281,958,750.58
31         DARE    $204,955,602.96

<h2>Which county has the most spending on opioids per capita?</h2>

<h1>Unemployment</h1>

<h2>Is there a correlation between unemployment rate and overdose deaths?</h2>

<h2>Is there a correlation between unemployment and spending on opioids?</h2>

<h1>Top prescribers</h1>

<h2>Where are the top 10 opioid prescribers located?</h2>

<h2>Who is the top prescriber in each county?</h2>

<h2>What proportion of opioids are prescribed by the top 10 prescribers?  Top 50? Top 100?</h2>

<h1>Nashville - Davidson County</h1>

<h2>Which zip codes in Davidson County have the most opioids prescribed?</h2>

<h2>Any correlation between the number of missed trash pick ups and number of opioids prescribed?</h2>